- name: Install Cluster Logging
  hosts: localhost
  tasks:
    - name: Create objects from the manifests
      k8s:
        state: "{{ k8s_state | default('present') }}"
        src: "{{ playbook_dir + '/' + item }}"
      loop:
        - logging-operator.yml
        - elasticsearch-operator.yml
        - event-router.yml
        - cl-minimal.yml
